### ISSUE TITLE
map unresponsive with a lot of markers

### ISSUE THREAD

**Issue by krisbulman** [Outdooractive/route-me#17]
After adding several hundred markers, I find local map sources almost unresponsive for zooming, or dragging the map. Is this a known problem? I've never had a problem doing the same with mapkit.

**Comment by mtoon** [comment]
You might be seeing the same thing I am...  it looks like the annotations are updated (and views updated subsequently) for any change in the map...  I don't have that many annotations, but I do update them when the bounds change and because the delegate methods are being called multiple times per single movement, it causes a lot of unnecessary processing.  Ideally, the mapViewRegionDidChange would fire after the decelleration..

**Comment by krisbulman** [comment]
I am simply looping through a local kml file using simple-kml to initially add the markers, and am doing nothing else but plotting them on the map. As soon as the markers are added, the map becomes barely usable. I have parsed local files using other methods with the same effect.

**Comment by trasch** [comment]
Please use cluster markers if possible (see the MarkerMurder sample), or create a demo project that shows the issue.

**Comment by krisbulman** [comment]
I have implemented the markers cluster sample, at zoom level 9, 890 markers load within one of the clusters and it takes over 30 seconds to count up before the map becomes active.

**Comment by krisbulman** [comment]
example project using Simple-KML here: https://github.com/krisbulman/IslandMap

**Comment by trasch** [comment]
I just added some improvements that should improve map responsiveness (currently only in the develop branch).

I'll have a look at your code later.

**Comment by krisbulman** [comment]
Tested the changes in dev branch, went from 15 seconds in the demo project I posted to 8 seconds

**Comment by krisbulman** [comment]
Pull request above resolved the issue I was experiencing, Thanks for the pull request Thomas, i learned something :)
