### ISSUE TITLE
Capturing RMMapView into UIImage

### ISSUE THREAD

**Issue by mtoon** [Outdooractive/route-me#27]
Just curious if this is possible..  The old way of drawing into a rect isn't working anymore.  I saw some closed issued around it, but I couldn't get it to work.  Any thoughts?  I only need to capture the current state of the map into a UIImage.

Thank you!

**Comment by trasch** [comment]
Have a look at the snapshot branch. It has some flaws, though...

**Comment by incanus** [comment]
What are those, exactly, out of curiosity? It's been working pretty well for me...

**Comment by trasch** [comment]
I do have some trouble to synchronize the marker overlay with the map snapshot at non-even zoom levels. I also changed how the tiles are drawn a bit (I think you're not using the last commit?), which works well but shows fine lines between tiles, due to rounding errors if I'm not mistaken. This definitly needs some more work to be universally usable...

**Comment by incanus** [comment]
Yeah, I do see the lines now that you mention it. Figured that was rounding. I will check that out.

**Comment by incanus** [comment]
To pick up this conversation again, Apple got back to me regarding a Radar on this with regard to `-renderInContext:`. They say: 

> -renderInContext: draws tiled layers by calling their -drawInContext: method, so it sounds like your draw method is not working correctly in this case.

I'll take a look at this. IIRC I played around with this back when I was debugging, but the work was different due to normalization of the layer coordinates.

**Comment by incanus** [comment]
So playing with `drawInContext:` in a `CATiledLayer` subclass doesn't seem to help here. But what I do notice is that different bounding boxes are passed to the context when you are getting normal tile requests and when you get a request via `renderInContext:`. Ordinarily, many tiles are requested and the bounding box is exactly the tile size. But during snapshots, only one request is made -- `CATiledLayer` doesn't figure out the individual requests for you. And this fails the current tile fetch routine, resulting in no valid images being drawn to the context. 

I was able to confirm this by also drawing a solid color into the context. When I take a snapshot, I get only the solid color out, so the routine is called, but no images are drawn atop the color. 

As a comparison, here are the calls for a 300x320 map view on load: 

```
2012-03-29 15:54:56.503 TiledLayerSnapTest[31687:11303] drawRect: {{135.250000,89.437500},{0.031250,0.031250}}
2012-03-29 15:54:56.504 TiledLayerSnapTest[31687:11203] drawRect: {{135.250000,89.468750},{0.031250,0.031250}}
2012-03-29 15:54:56.510 TiledLayerSnapTest[31687:11303] drawRect: {{135.250000,89.468750},{0.031250,0.031250}}
2012-03-29 15:54:56.511 TiledLayerSnapTest[31687:11203] drawRect: {{135.281250,89.437500},{0.031250,0.031250}}
2012-03-29 15:54:56.514 TiledLayerSnapTest[31687:11303] drawRect: {{135.281250,89.437500},{0.031250,0.031250}}
2012-03-29 15:54:56.516 TiledLayerSnapTest[31687:11203] drawRect: {{135.218750,89.437500},{0.031250,0.031250}}
2012-03-29 15:54:56.519 TiledLayerSnapTest[31687:11303] drawRect: {{135.218750,89.437500},{0.031250,0.031250}}
2012-03-29 15:54:56.521 TiledLayerSnapTest[31687:11203] drawRect: {{135.250000,89.406250},{0.031250,0.031250}}
2012-03-29 15:54:56.524 TiledLayerSnapTest[31687:11303] drawRect: {{135.250000,89.406250},{0.031250,0.031250}}
2012-03-29 15:54:56.525 TiledLayerSnapTest[31687:11203] drawRect: {{135.281250,89.468750},{0.031250,0.031250}}
2012-03-29 15:54:56.529 TiledLayerSnapTest[31687:11303] drawRect: {{135.281250,89.468750},{0.031250,0.031250}}
2012-03-29 15:54:56.530 TiledLayerSnapTest[31687:11203] drawRect: {{135.218750,89.468750},{0.031250,0.031250}}
2012-03-29 15:54:56.535 TiledLayerSnapTest[31687:11303] drawRect: {{135.218750,89.468750},{0.031250,0.031250}}
2012-03-29 15:54:56.536 TiledLayerSnapTest[31687:11203] drawRect: {{135.281250,89.406250},{0.031250,0.031250}}
2012-03-29 15:54:56.565 TiledLayerSnapTest[31687:11303] drawRect: {{135.281250,89.406250},{0.031250,0.031250}}
2012-03-29 15:54:56.575 TiledLayerSnapTest[31687:11203] drawRect: {{135.218750,89.406250},{0.031250,0.031250}}
2012-03-29 15:54:56.617 TiledLayerSnapTest[31687:11303] drawRect: {{135.218750,89.406250},{0.031250,0.031250}}
```

And here is the one from `renderInContext:`: 

```
2012-03-29 15:55:09.083 TiledLayerSnapTest[31687:f803] drawRect: {{135.248047,89.436646},{0.039062,0.036621}}
```

If we can figure out how to get from the the latter to manually making the calls like the former, we can do so and those images will be drawn into the context. We won't have to crop since the context is already sized the same as the view.

**Comment by trasch** [comment]
Ok, I'll have a look at this as soon as I find some spare time.

**Comment by trasch** [comment]
Great, exactly the hint that I needed, thanks! I rewrote the snapshot code and commited it to the snapshot branch. It would be great if everyone interested in this feature could test it, I'll merge it into the release branch then.

**Comment by incanus** [comment]
I will check this out, but one thing that jumps out at me is the push/pop context calls, which will happen on background threads and shouldn't. I think we'll have to use the CG routines and a context transformation (to flip the image) in order to draw it instead of `drawInRect:`.

**Comment by mtoon** [comment]
A little off-topic, but is there a way to create a snapshot of a particular bounding box through the API only?  Basically I'd like to be able to pass in:
UIImage *i = [mapView createSnapShotFor:<UpperLeft Coordinate> lowerRight:<LowerRight Coordinate> maxSize:(CGSize - eg. 1024x1024)] and have the mapView automatically select the zoom level and create the image. It could be scaled afterwards to the maxSize.  Thoughts?  I could move this to an additional issue, but thought it might be simple with a little push in the right direction.  Thank you!

**Comment by incanus** [comment]
@mtoon Pretty sure you'd have to do this via an actual view. Depending on if your map view has delegate callbacks based on configuration changes, you might have to create a new, second map view for this purpose, but then set the coords & take the snapshot before removing it.

**Comment by mtoon** [comment]
@incanus Thanks for the quick reply.  I noticed the way the snapshots used to work using a passed in bounding box was sent in.  If I wanted to create multiple images quickly using the method would it be possible to use the new code that's been generated, but use a parameter for the bounding box instead of the currently assigned one?  I need to generate these images fairly quickly and I'm worried that the overhead of actually instantiating a view and manipulating it will cause a big slowdown.  Thank you!

**Comment by trasch** [comment]
@incanus I think the push/pop context calls should be thread safe even if the documentation says otherwise (see http://developer.apple.com/library/ios/#qa/qa1637/_index.html). I am gambling here, I admit... :) Another issue is that the performance implications of using UIKit here is unclear, but IMO negligible.

**Comment by trasch** [comment]
@mtoon The snapshot feature is at this moment only inteded to be WYSIWYG. The old implementation was a hack since it basically replicated the map view by manually assembling the tiles. If you need more flexibility, you could just take the old implementation in your project and fit it to your needs. Be aware though that the old code didn't work well with overlays.
Another option would be to create two map views, one for the screen and one for offline usage. You could set the same map source and tile cache for both of them, so the memory consumption shouldn't be too bad.

**Comment by incanus** [comment]
@trasch, this is looking good. I might take a crack at the CG stuff to avoid the UIKit use in the background threads, but I agree we're probably ok here. 

I do see the tile border lines sometimes as per the old version, likely still due to rounding. But all in all, pretty nice.

**Comment by trasch** [comment]
I just merged the snapshot branch to the develop branch. If there are no objections, I'll merge it to the release branch next week or so...

**Comment by MattFoley** [comment]
I'm interested in picking up where you guys left off and fixing the lines that show up occasionally. I looked at it, and then tugged on a few things but didn't have much success. Any advice on the direction you were headed in last time you looked at this bit of code?

**Comment by incanus** [comment]
Hmm, I don't see lines from that. Any idea what sort of conditions cause this?

**Comment by MattFoley** [comment]
I'm not sure, I see it consistently, but they vary from slight faint lines, to strong lines 1 or 2 pixels across.

Also, you don't really see them on the iPhone screen until you put the screenshot into an editing context where you can zoom in and really see the detail. (Once you know where they are, they stand out)

For more info, we're using a custom tile provider I added into the framework on my fork of Mapbox, which split from the release branch about 3 weeks ago. Tiles are generally about 384px square, but that's defined by the individual  map that is being displayed.

![mapcraft](https://f.cloud.github.com/assets/1182042/172641/6dd1bf9e-7ac2-11e2-9e9b-1d89ad0d8c94.png)

**Comment by incanus** [comment]
Whoa, awesome screenshot. I've split this issue off into a separate one above since this original is closed.
