### ISSUE TITLE
Panning through date line ?

### ISSUE THREAD

**Issue by tom34** [Outdooractive/route-me#45]
As far as i know it's impossible to cross the data line (= longitude 180) while panning the map.

Is there a way to enable this functionality using the Alpstein fork ?

**Comment by trasch** [comment]
There is no easy way to get this to work since the underlying `CATiledLayer` doesn't support it (and therefore Apple's own Maps application).

If you really want to bang your head against a wall you can have a look at the `endlessscroll1` branch. I created it some time ago to test the feasability of this but haven't pursued it.

**Comment by tom34** [comment]
Ok thanks for your reply.
No joy, i will revert to the "original" Route-Me. 
A bit sad because i think that the CATiledLayer is a nice approach.
Thanks again.
