### ISSUE TITLE
RMPath - Bogus Layer Size?

### ISSUE THREAD

**Issue by mtoon** [Outdooractive/route-me#53]
I get this a lot when I use RM paths that are fairly distant.  Any thoughts?

-[<RMPath: 0x82e9c0> display]: Ignoring bogus layer size (116573.312500, 7702.689941)

Thank you!
-Malcolm

**Comment by jan-christiansen** [comment]
I think the reason for this problem are described in issue #29. You can check out the branch called `without_observer` of my route-me fork, where I have tried to fix this issue. You would have to use the class `RMShape` instead of `RMPath` to use the fork as I did not fix the `RMPath` implementation but the interfaces are quite similar. However, note that the implementation is not fully tested and might have other issues.

**Comment by jan-christiansen** [comment]
After googling the error it seems more likely that your path is simply too large to be drawn to a single layer. Therefore, decomposing the path into several paths might be a solution.

**Comment by trasch** [comment]
It might also be that there are too many paths on the map/screen.
