### ISSUE TITLE
`RMMapScrollViewDelegate` should be private

### ISSUE THREAD

**Issue by incanus** [Outdooractive/route-me#89]
The `RMMapScrollViewDelegate` protocol shouldn't be seen by devs just using `RMMapView.h` and is confusing when what is meant is `RMMapViewDelegate`. We should hide it somehow to avoid confusion.

**Comment by trasch** [comment]
I don't think that there is an elegant way to hide it since the compiler needs to see it.

Why exactly do you think this is a problem? A dev should be able to differentiate  between an implemented protocol and a delegate protocol, but we could rename it to something like `RMInternalConstraintsDelegate` if you want (that at least would be easy... :)

**Comment by incanus** [comment]
Yeah, I guess it's not too confusing. Just a cleanup issue. It's not a big deal.
